### ISSUE TITLE
inference CUDA OutOfMemoryError

### ISSUE THREAD

**Issue by SuSung-boy** [zhengchen1999/RGT#11]
when I was inference, always get the error OOM

But I use 80G GPU, every time the code excute to q @ v , will cause OOM , and it will collect over 50G GPU memory, which I think is abnormal

And my input image shape is (750, 1000)

do u know how to fix it?

**Comment by zhengchen1999** [comment]
The images are too large, consider chrop them. Specifically, you can modify the [yml](https://github.com/zhengchen1999/RGT/blob/main/options/test/test_RGT_S_x2.yml#L84) settings as follows:
`use_chop: True`.

**Comment by SuSung-boy** [comment]
Thanks, it works
